import { CompanionOptionValues, CompanionVariableDefinition } from '@companion-module/base'
import type { RCVInstance } from '../index.js'


export function UpdateVariableDefinitions(instance: RCVInstance): void {
	instance.variables = [
		{ variableId: 'show_name', name: 'Show Name' },
		{ variableId: 'device_fanspeed', name: 'Device Fan Speed' },
		{ variableId: 'switching_mode', name: 'Switching Mode' },
		{ variableId: 'frame_rate', name: 'Frame Rate' },
		{ variableId: 'stream_timecode', name: 'Stream Timecode' },
		{ variableId: 'record_timecode', name: 'Record Timecode' },
		{ variableId: 'audio_delay_frames', name: 'Audio Delay (Frames)' },
		{ variableId: 'audio_delay_ms', name: 'Audio Delay (ms)' },
		{ variableId: 'transition_time', name: 'Transition Time' },
		{ variableId: 'input_1_name', name: 'Input 1 Name' },
		{ variableId: 'input_2_name', name: 'Input 2 Name' },
		{ variableId: 'input_3_name', name: 'Input 3 Name' },
		{ variableId: 'input_4_name', name: 'Input 4 Name' },
		{ variableId: 'input_5_name', name: 'Input 5 Name' },
		{ variableId: 'input_6_name', name: 'Input 6 Name' },
		{ variableId: 'scene_A_name', name: 'Scene A Name' },
		{ variableId: 'scene_B_name', name: 'Scene B Name' },
		{ variableId: 'scene_C_name', name: 'Scene C Name' },
		{ variableId: 'scene_D_name', name: 'Scene D Name' },
		{ variableId: 'scene_E_name', name: 'Scene E Name' },
		{ variableId: 'scene_F_name', name: 'Scene F Name' },
		{ variableId: 'scene_G_name', name: 'Scene G Name' },
		{ variableId: 'media_A_name', name: 'Media A Name' },
		{ variableId: 'media_B_name', name: 'Media B Name' },
		{ variableId: 'media_C_name', name: 'Media C Name' },
		{ variableId: 'media_D_name', name: 'Media D Name' },
		{ variableId: 'media_E_name', name: 'Media E Name' },
		{ variableId: 'media_F_name', name: 'Media F Name' },
		{ variableId: 'media_G_name', name: 'Media G Name' },
		{ variableId: 'overlay_A_name', name: 'Overlay A Name' },
		{ variableId: 'overlay_B_name', name: 'Overlay B Name' },
		{ variableId: 'overlay_C_name', name: 'Overlay C Name' },
		{ variableId: 'overlay_D_name', name: 'Overlay D Name' },
		{ variableId: 'overlay_E_name', name: 'Overlay E Name' },
		{ variableId: 'overlay_F_name', name: 'Overlay F Name' },
		{ variableId: 'overlay_G_name', name: 'Overlay G Name' },
		{ variableId: 'wireless1_connected', name: 'Wireless 1 Connected' },
		{ variableId: 'wireless1_signal', name: 'Wireless 1 Signal Strength' },
		{ variableId: 'wireless1_battery', name: 'Wireless 1 Battery Level' },
		{ variableId: 'wireless1_charging', name: 'Wireless 1 Charging' },
		{ variableId: 'wireless1_muted', name: 'Wireless 1 Onboard Mute' },
		{ variableId: 'wireless1_record', name: 'Wireless 1 Onboard Record' },
		{ variableId: 'wireless2_connected', name: 'Wireless 2 Connected' },
		{ variableId: 'wireless2_signal', name: 'Wireless 2 Signal Strength' },
		{ variableId: 'wireless2_battery', name: 'Wireless 2 Battery Level' },
		{ variableId: 'wireless2_charging', name: 'Wireless 2 Charging' },
		{ variableId: 'wireless2_muted', name: 'Wireless 2 Onboard Mute' },
		{ variableId: 'wireless2_record', name: 'Wireless 2 Onboard Record' },
		{ variableId: 'storage_usb_data_used', name: 'USB Storage Data Used (Bytes)' },
		{ variableId: 'storage_usb_data_remain', name: 'USB Storage Data Remaining (Bytes)' },
		{ variableId: 'storage_usb_percent', name: 'USB Storage Percentage Full' },
		{ variableId: 'storage_sd_data_used', name: 'SD Card Data Used (Bytes)' },
		{ variableId: 'storage_sd_data_remain', name: 'SD Card Data Remaining (Bytes)' },
		{ variableId: 'storage_sd_percent', name: 'SD Card Percentage Full' },
	]

	instance.setVariableDefinitions(instance.variables);

	instance.setVariableValues({
		'show_name': '',
		'device_fanspeed': '0',
		'switching_mode': '',
		'stream_timecode': '00:00:00',
		'record_timecode': '00:00:00',
		'audio_delay_frames': '0',
		'audio_delay_ms': '0',
		'transition_time': '0',
		'frame_rate': '0',
		'input_1_name': 'Unassigned',
		'input_2_name': 'Unassigned',
		'input_3_name': 'Unassigned',
		'input_4_name': 'Unassigned',
		'input_5_name': 'Unassigned',
		'input_6_name': 'Unassigned',
		'scene_A_name': 'Unassigned',
		'scene_B_name': 'Unassigned',
		'scene_C_name': 'Unassigned',
		'scene_D_name': 'Unassigned',
		'scene_E_name': 'Unassigned',
		'scene_F_name': 'Unassigned',
		'scene_G_name': 'Unassigned',
		'media_A_name': 'Unassigned',
		'media_B_name': 'Unassigned',
		'media_C_name': 'Unassigned',
		'media_D_name': 'Unassigned',
		'media_E_name': 'Unassigned',
		'media_F_name': 'Unassigned',
		'media_G_name': 'Unassigned',
		'overlay_A_name': 'Unassigned',
		'overlay_B_name': 'Unassigned',
		'overlay_C_name': 'Unassigned',
		'overlay_D_name': 'Unassigned',
		'overlay_E_name': 'Unassigned',
		'overlay_F_name': 'Unassigned',
		'overlay_G_name': 'Unassigned',
		'wireless1_connected': 'false',
		'wireless1_signal': '0',
		'wireless1_battery': '0',
		'wireless1_charging': 'false',
		'wireless1_muted': 'false',
		'wireless1_record': 'false',
		'wireless2_connected': 'false',
		'wireless2_signal': '0',
		'wireless2_battery': '0',
		'wireless2_charging': 'false',
		'wireless2_muted': 'false',
		'wireless2_record': 'false',
		'storage_usb_data_used': '0',
		'storage_usb_data_remain': '0',
		'storage_usb_percent': '0',
		'storage_sd_data_used': '0',
		'storage_sd_data_remain': '0',
		'storage_sd_percent': '0'
	});
}